historical_figures = [
    # Ancient Era
    "Gilgamesh",
    "Hammurabi",
    "Moses",
    "Ramses II",
    "Confucius",
    "Socrates",
    "Plato",
    "Aristotle",
    "Alexander the Great",
    "Archimedes",
    "Julius Caesar",
    "Cleopatra",
    "Qin Shi Huang",
    "Cao Cao",
    "Sun Tzu",
    "Zhuge Liang",
    # Middle Ages
    "Charlemagne",
    "Genghis Khan",
    "Saladin",
    "Leonardo da Vinci",
    "Joan of Arc",
    "Mansa Musa",
    "Ibn Battuta",
    # Renaissance & Enlightenment
    "Michelangelo",
    "Galileo Galilei",
    "Isaac Newton",
    "William Shakespeare",
    "Wolfgang Amadeus Mozart",
    # Science & Technology
    "Nikola Tesla",
    "Marie Curie",
    "Albert Einstein",
    "Ada Lovelace",
    "Charles Darwin",
    "Alan Turing",
    "Thomas Edison",
    # Medicine
    "Florence Nightingale",
    "Hippocrates",
    "Louis Pasteur",
    "Alexander Fleming",
    # Politics & Leadership
    "Winston Churchill",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Catherine the Great",
    # Exploration
    "Marco Polo",
    "Christopher Columbus",
    "Amelia Earhart",
    "Neil Armstrong",
    # Philosophy & Thought
    "Friedrich Nietzsche",
    "Karl Marx",
    "Simone de Beauvoir",
    # Arts & Literature
    "Frida Kahlo",
    "Pablo Picasso",
    "Jane Austen",
    "Leo Tolstoy",
]
